### ISSUE TITLE
[EPIC] Create a JH analysis service that recommends resource tiers

### ISSUE THREAD

**Issue by Shreyanand** [aicoe-aiops/operate-first-jupyterhub-analysis#35]
To make resource recommendation more easily accessible, we should create an AIOps service for it. 

The service should have following components from a technical standpoint:

- [ ] Given a cluster URL with Jupyterhub and Prometheus instance, fetch relevant metrics for the desired frequency
- [ ] Run model training
- [ ] Output recommended resource allocation policy for t-shirt size
- [ ] Optional: Output user specific recommendation by inferring from trained model
